### ISSUE TITLE
Abundance of Clay

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#100]
There is a lot of clay. Entirely too much, if I were to be asked. In 1.6, was it not on par with vanilla iron generation? I don't know what it is at right now, but it doesn't feel quite right.

**Comment by esKaayY** [comment]
Already fixed https://github.com/TPPIDev/TestPackPleaseIgnore2/commit/d80486716dae167c32e81e5a4792373b61f64ad7
