### ISSUE TITLE
Tantalite is practically invisible

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#101]
Exactly what the title says, it is almost the exact same texture as stone. 
https://imgur.com/EuA7nJ1

Iridium is almost the same, but that might be alright

**Comment by Sovereignty89** [comment]
Yea Nut! Hell this ore is brownish/redish in Gregtech!

**Comment by TehNut** [comment]
No it's not... I literally looked at the textures side by side and they're pretty much the same.

**Comment by tterrag1098** [comment]
$5 says Greg colors it in the rendering

**Comment by TehNut** [comment]
He does
