### ISSUE TITLE
Moss Stone Recipe conflict

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#102]
Crafting 9 moss stone as one would to make a ball of moss does not return said ball of moss but in fact returns compressed cobblestone.

**Comment by TehNut** [comment]
uw0tm8

**Comment by HaroldDaFrog** [comment]
Moss stone and cobble seem to be predicted, which could prove to be annoying with crafting in ae and whatnot

**Comment by esKaayY** [comment]
Solution would be to un-oreDict mossy stone.
