### ISSUE TITLE
Aluminium Ingots auto unifying from TiC to GT and causing problems.

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#104]
Annoying because I can't make it into blocks unless I pull it out of the smeltery via casting basin.

http://puu.sh/e0bnL/f117a6d85e.jpg

Also when it auto unifies to GT aluminium it cannot be used in smeltery again.

**Comment by TehNut** [comment]
Did we not turn off Greg's shitty unification stuff?

**Comment by HaroldDaFrog** [comment]
Nope! All sorts of stuff is switching around

**Comment by TehNut** [comment]
I checked and inventory unification is disabled, only crafting is left on. It shouldn't cause this issue...

**Comment by esKaayY** [comment]
Fixed it here: https://github.com/TPPIDev/TestPackPleaseIgnore2/commit/f35597dd20e126fbd4a700d48bcf9dd5177ab992
