### ISSUE TITLE
Weird Crash with chisel

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#105]
http://pastebin.com/yBdT5rJV
So this happened. I have experienced something like this before, it seems to happen when you do a weird combination of shift and number clicking at the same time while in the chisel interface. I can't replicate it, I have no idea if anything can fix this, but I thought I'd post it.

**Comment by TehNut** [comment]
I'm going to close this since you can't replicated it. If you manage to reproduce (and are able to do so multiple frequently) I will reopen it.
