### ISSUE TITLE
Unable to craft Tin Plates with Rolling Machine

### ISSUE THREAD

**Issue by Sovereignty89** [TPPIDev/TestPackPleaseIgnore2#111]
Unable to craft tin plates with the rolling machine. The recipe shows up in NEI, but the tin ingots interchange with iron ingots within NEI. On top of that, no type of tin ingot works. Done it with TE and TC tin ingot.

http://i.imgur.com/o9qnBKe.png
http://i.imgur.com/hPW6lGm.png
http://i.imgur.com/Z3EAHNt.png

**Comment by tterrag1098** [comment]
The recipe requires 2 tin and 2 iron...

**Comment by Sovereignty89** [comment]
That is just weird.

**Comment by Sovereignty89** [comment]
http://puu.sh/e48X5.png

**Comment by tterrag1098** [comment]
That's the RC recipe and has been for a while.
