### ISSUE TITLE
MFR Harvester + IC2 Crops Cross mod issue.

### ISSUE THREAD

**Issue by calmcacil** [TPPIDev/TestPackPleaseIgnore2#112]
Currently it seems that the MFR harvester will not harvest IC2 Potato crops unless they turn into poisonous potatoes. I'm not sure if this is intended or not.

Reproduction:
1. MFR Harvester.
2. IC2 Crops with Potato planted.
3. Lots of waiting.

**Comment by TehNut** [comment]
Have they ever worked?

**Comment by calmcacil** [comment]
I'm not completely sure, I know the MFR harvester will harvest just a about anything. including potatoes. Could be IC2 Crops dont report potatoes as done until after they've gone bad.

**Comment by TehNut** [comment]
Well, the IC2 crop potatoes aren't normal potatoes. It may not be compatible.

**Comment by Sovereignty89** [comment]
MFR never worked with IC2 crops. IC2 and GT add their own machines to handle their crops.

**Comment by calmcacil** [comment]
@Sovereignty89 oh? It works for everything other than potatoes though.

**Comment by Sovereignty89** [comment]
Hmm, I never got the crops to work with MFR, might be a recent change.

**Comment by TehNut** [comment]
Since it's not really intended to work, it's not really a bug...
