### ISSUE TITLE
Lumber Axe breaks Livingwood back into regular wood

### ISSUE THREAD

**Issue by Trostmm** [TPPIDev/TestPackPleaseIgnore2#113]
Using a lumber axe on Livingwood breaks it back into regualr wood.

**Comment by Rapthera** [comment]
I can't seem to replicate this issue.

I've just cut down livingwood with a lumber axe and it returned me the livingwood.

**Comment by Iwerks** [comment]
Same here. I used my lumber axe & hammer to get living wood and rock and had no problems.

Maybe you didn't wait long enough for it to swap out fully?

**Comment by Trostmm** [comment]
I can get it to fail about 50% of the time, think it might just be a quirk in my layout, cause if I seperate the flowers it doesn't happen anymore.

**Comment by tterrag1098** [comment]
It's the usual client/server desync the pure daisy has had since it was added.
