### ISSUE TITLE
Kick from server by crafting torches.

### ISSUE THREAD

**Issue by ryanayoung** [TPPIDev/TestPackPleaseIgnore2#115]
Repeatable.  Right clicking to craft multiple torches when you have a large amount of coal(54ish or more) but only a small amount of sticks(4ish), will kick you from the server.

**Comment by TehNut** [comment]
Does client or server have Mini Coal from Ztones enabled while the other doesn't?

**Comment by tterrag1098** [comment]
Need server log too.

**Comment by ryanayoung** [comment]
Okay, it does seem to be min-coal.  Had never seen that mod before.  Just putting coal in the grid shows mini-coal in the output, but grabbing it crashes game.

I don't know if it's enable on the server.
here's the crash log.  http://pastebin.com/yaesPtbL

I imagine that's the problem if you've seen this before.

**Comment by TehNut** [comment]
If using our configs, it shouldn't be enabled. Disable for fix.
