### ISSUE TITLE
No Zinc Spawning

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#116]
Flaxbeard's Steam Power brass is incredibly hard to make with having only poor zinc ore spawning (which I think is now turned off for newer chunks). I think a few maps ago when the configs derped someone turned the Zinc off and it went unnoticed last map.

With this being said the mod is incredibly hard to get started in seeing as it is a great early to mid game mod.

**Comment by esKaayY** [comment]
Need to COFH world gen it.

**Comment by esKaayY** [comment]
https://github.com/TPPIDev/TestPackPleaseIgnore2/commit/1e4cd84e6d13f6bb0a24cf0a040005ff2f52902b Closing
