### ISSUE TITLE
Mekanism Circuits Auto Unification

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#118]
Mekanism Circuits auto unify to IC2 circuits when thrown on the ground similar to the essence berries to ore berries.

**Comment by TehNut** [comment]
I SAID MIGHT, NOT WILL. STUPID COMMIT CLOSING THINGS.

**Comment by UndeadZeratul** [comment]
Don't you just love being able to close issues automatically with commit comments?  Aren't they just the best?

**Comment by esKaayY** [comment]
Duplicate of https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/92
