### ISSUE TITLE
Unstable Ingot Safe crafting into nuggets -> ingots still explodes.

### ISSUE THREAD

**Issue by Rapthera** [TPPIDev/TestPackPleaseIgnore2#119]
As title says, it explodes even though its supposed to be stable.

**Comment by tterrag1098** [comment]
I blame greg.

**Comment by esKaayY** [comment]
@tterrag1098 didn't we have code setup to un-oreDict this in 1.6?

**Comment by HaroldDaFrog** [comment]
No longer an issue as of Hopefully Killable

**Comment by TehNut** [comment]
Confirmed not an issue?

**Comment by Rapthera** [comment]
Not a issue anymore.
