### ISSUE TITLE
EnderIO's Soul Binder cannot accept more experience and is stuck.

### ISSUE THREAD

**Issue by Rapthera** [TPPIDev/TestPackPleaseIgnore2#122]
EnderIO's Soul binder cannot accept any more experience while a 1/10 is needed to complete the ten levels.

http://puu.sh/ecUnD/b5226b979f.jpg

no matter how many times I hit that, It will not fill up.

After further testing, the Ender Crystal cannot seem to be made but the Powered Spawner (chaning types) can.

**Comment by reality404** [comment]
My EnderIO Soul binder Goes up to 41 experience https://i.imgur.com/whccWpG.png and I can craft Ender Crystals.
