### ISSUE TITLE
Random Things Overpowered Item

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#124]
The "magnetic force" from Random Things allows you to teleport to any player anywhere on the server, for the cost of one emerald, one ender pearl, and one piece of paper. For oblivious reasons, this could kind of mess up certain server types, and could be used for very evil purposes. I'd suggest either removing it, or making it require nether stars or something.

**Comment by TehNut** [comment]
I hate it when oblivious issues like this slip past us.

**Comment by HaroldDaFrog** [comment]
Isn't this what we're here for? ^_^
