### ISSUE TITLE
Blocks of metals uncraftable now.

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#129]
http://puu.sh/eh22B/c52b9b9966.jpg

Also copper switched to GT after processing and won't unify to TE so I don't waste space in my AE.

-_-;

**Comment by TwiiCe** [comment]
A quick workaround (for the time being) is to melt them in a smeltry and dump the contents of the smeltry in a casting basin.
(The TiCo Crucible)

**Comment by esKaayY** [comment]
Duplicate of https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/120

**Comment by TehNut** [comment]
No, the blocks themselves are uncraftable. #120 is saying that uncrafting a block turns it to dusts.
