### ISSUE TITLE
Obsidian pulverizes to 9 dust

### ISSUE THREAD

**Issue by MikeLydeamore** [TPPIDev/TestPackPleaseIgnore2#131]
This is instead of the usual 4. Actually a buff.
Also, you can craft the obsidian into 9 dust directly, and then use it for the hardened glass.

**Comment by esKaayY** [comment]
Closed here https://github.com/TPPIDev/TestPackPleaseIgnore2/commit/e0a48139ce0a2515dee8a21bbb960e052c8f719d
