### ISSUE TITLE
EnderIO ME Conduits connection issue.

### ISSUE THREAD

**Issue by calmcacil** [TPPIDev/TestPackPleaseIgnore2#133]
Currently it seems like EIO's ME conduits dont care if you use a wrench to disable their connection, they seem like they currently are connected even if you disable the connection. They also seem not update in world when you break a connected device/cable. 

http://puu.sh/elkCR/cd386f00eb.jpg

**Comment by HaroldDaFrog** [comment]
Yep, I've encountered this same thing. All we can do is blame Tterrag until EIO cleans it up a bit, not a huge problem.

**Comment by TehNut** [comment]
Cannot reproduce.

![Nope][http://puu.sh/fgZ7H/d030e02e39.png]

**Comment by calmcacil** [comment]
Try connecting it to something that isnt another EIO conduit and then break whatever it was connected to. I.e. Connect a ME Drive  and then break the drive.

**Comment by TehNut** [comment]
Ah, I see. Yup

**Comment by tterrag1098** [comment]
Is fixed in EIO dev builds

**Comment by TehNut** [comment]
Coolio
