### ISSUE TITLE
Basic (Diamond) tools not breaking when damage value is 0.

### ISSUE THREAD

**Issue by TwiiCe** [TPPIDev/TestPackPleaseIgnore2#136]
I haven't tried this with other tools then diamond ones, but once their damage value is 0, where it would normally break, it breaks but reappears in the inventory.
You can use the tool over and over and the damage value goes into negatives.
The tool keeps breaking and reappearing.

This works for shovels, axes and pickaxes.
The only exception is if an item is picked up, to fill the old slot the tool used to be in, before the item can reappear in the inventory.

Reproduce:
Make diamond tool, use it until it's empty. 
It does not break.
I can provide the negative damage values tools if wished.
IGN: TwiiCe

**Comment by HaroldDaFrog** [comment]
No longer an issue, works as intended.
