### ISSUE TITLE
Iron Buckets uncraftable in TiCo Crafting Table

### ISSUE THREAD

**Issue by TwiiCe** [TPPIDev/TestPackPleaseIgnore2#137]
You cant craft buckets in a TiCo Crafting table.
Neither can you craft iron tools.
(Maybe the iron ingot is bugged?)

**Comment by TwiiCe** [comment]
Hoppers, Tools.. Anything Iron does not go well with the TiCo Table..

**Comment by MikeLydeamore** [comment]
I can craft a bucket in a Tinkers Table just fine though.
