### ISSUE TITLE
EnderIO Fluid Conduit not pumping out of Black Hole Storage

### ISSUE THREAD

**Issue by MikeLydeamore** [TPPIDev/TestPackPleaseIgnore2#142]
Neither myself nor Yoyoto could work out why.

**Comment by MikeLydeamore** [comment]
This is apparently a known issue, using pressurised or above works. No idea why.

**Comment by HaroldDaFrog** [comment]
Seems reasonable to me, its pretty hard to get out of a black hole

**Comment by TehNut** [comment]
New feature caused by a bug. I like it. ;)

**Comment by tterrag1098** [comment]
But...its a bug
