### ISSUE TITLE
tinker's armor starts with night vision

### ISSUE THREAD

**Issue by Cyrakrum** [TPPIDev/TestPackPleaseIgnore2#145]
The tinker's construct helmet (Traveller's goggles) seems to inherently start with night vision. This is also incorrectly shown as "Ability: Swap HotbarG"

**Comment by TehNut** [comment]
Well, the night vision is a feature of them. It's not really gamebreaking so that can stay. As for the tooltip, that seems to not be there anymore. Says the correct thing, now.
