### ISSUE TITLE
Ztones don't work with camouflage blocks from SFM 

### ISSUE THREAD

**Issue by GonzaloXavier** [TPPIDev/TestPackPleaseIgnore2#146]
They render the cable texture instead of the Ztone block texture.

**Comment by tterrag1098** [comment]
:<

**Comment by tterrag1098** [comment]
Probably just the special renderer of the ZTones stuff conflicting. Not sure why SFM couldn't support that though. EIO does it.

**Comment by TehNut** [comment]
Fixed according to https://github.com/Vswe/ModJam3/issues/82
