### ISSUE TITLE
Unable to craft Arcane Assembler

### ISSUE THREAD

**Issue by Rapthera** [TPPIDev/TestPackPleaseIgnore2#148]
Due to the silverwood thaumium bossed wand having a damaged value, causes it to be uncraftable.

**Comment by Professor29** [comment]
To explain: The infusion recipe for the Arcane Assembler doesn't function due to a Silverwood Crafting Sceptre having a metadata of 81 when crafted, as opposed to the 128 that is shown in both the recipe and NEI.

**Comment by FakoTheGreat** [comment]
Fixed via update to Thaumic Energistics.
