### ISSUE TITLE
[Suggestion] Enable the EnderIO recipes for MFR

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#152]
As title says. The recipes take a bit more mid-game stuff, and would keep MFR and EIO on similar levels at least in terms of recipes.

**Comment by TehNut** [comment]
We were already planning on enabling the TE recipes. Just haven't, yet.

**Comment by tterrag1098** [comment]
Por que no los dos?

**Comment by TehNut** [comment]
Because EnderIO already has many features added by MFR. Why double up on the stuff behind that tech tree?

**Comment by Iwerks** [comment]
I rather have TE recipes for the machines for reasons Nut just stated.

**Comment by tterrag1098** [comment]
As I said, why not both? I don't see it as "gating" it behind any tech tree, but rather allowing people who do either to still craft MFR stuff.

**Comment by FakoTheGreat** [comment]
Was discussed.  Considering the fact that EnderIO can create most of the Thermal Expansion materials already, there's no need to add a second expensive recipe that would just be ignored by the vast majority of players.  Closing issue.
