### ISSUE TITLE
Block of Charcoal from Tinker's Steelworks

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#153]
I can't find it in NEI and I was using them for my High Boiler... :(

**Comment by Professor29** [comment]
Collateral damage from updating Tinkers in the newest test setup.  Sadly, Tinkers Steelworks hasn't received an update in months, and even that update was an unofficial fork.

**Comment by Ephys** [comment]
Did another mod add a charcoal block ? That might have caused it (because my code is broken, I'll see if I can fix that)

**Comment by FakoTheGreat** [comment]
The block returned when I downgraded Mekanism in the test setup, and I know that Mekanism has a charcoal block (for storage, not fuel).

**Comment by Ephys** [comment]
The latest version of TSteelworks allows the use of mekanism charcoal blocks as fuel

**Comment by FakoTheGreat** [comment]
Awesome, thank you

**Comment by FakoTheGreat** [comment]
Fixed as of latest alpha setup. Closing issue.
