### ISSUE TITLE
[GT] I cant make any of the small batteries

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#157]
There is no way to get either of the 4 materials required.
Mercury/Cadmium/Lithium/Sodium

**Comment by tjsd** [comment]
Seems I can make lithium from clay, so that is covered

**Comment by esKaayY** [comment]
@tjsd So, they're craftable now AKA this is not an issue anymore?

**Comment by tjsd** [comment]
yes with sodium, lithium needs MV, but that is expected since its higher tier. Sov has been excellent in explaining how to greg :)
