### ISSUE TITLE
Client kick -  Hopefully Greggified - when I access AE terminal

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#158]
http://i.imgur.com/fWS6fbF.png < worth more then a 1000 words, but if you are so inclined http://paste.ee/p/tT2JS

There is nothing wrong in the log, but it just suddenly started to happen after I tried to make a soft hammer. I placed 6 oak wood planks in a door pattern and I crashed. When I try to make a door in a regular crafting bench I get strange error graphic (black/pink squares). 

Sverd/Calmacil base up in the sky.

**Comment by tjsd** [comment]
just got sovereignty89 to craft a door from oak wood planks in AE crafting terminal and he insta crashed aswell.

**Comment by Sovereignty89** [comment]
Created an iron door as well, get a pink/black checkered box that disappears in a normal crafting bench but causes http://puu.sh/ezrSV.png when done in AE

**Comment by FakoTheGreat** [comment]
It looks like we might have Malisis Doors to thank for this.  Basing this on [url]http://minecraft.curseforge.com/mc-mods/223891-malisis-doors/files/2224764[/url]
