### ISSUE TITLE
Travel anchor protection isn't secured

### ISSUE THREAD

**Issue by Cyrakrum** [TPPIDev/TestPackPleaseIgnore2#161]
The password lock on travel anchors is very easily bypassed. If you attempt to use it as it's highlighted after being previously denied you can use said anchor. Also if looking at an anchor you can movie around indefinitely? and still use the anchors

**Comment by Rapthera** [comment]
This is similar to issue #150

**Comment by esKaayY** [comment]
Duplication of #150, look at the issues first before posting a new one
