### ISSUE TITLE
Random Things Advanced Item Collector Recipe

### ISSUE THREAD

**Issue by FakoTheGreat** [TPPIDev/TestPackPleaseIgnore2#162]
Putting this as a note that the advanced item collector from RT needs its cost increased, as it provides better functionality than an EnderIO Vacuum Chest for far cheaper.

**Comment by esKaayY** [comment]
This really isn't milestone worthy

**Comment by FakoTheGreat** [comment]
Been implemented for a while, simply forgot to close the issue. Sorry about that.
