### ISSUE TITLE
Cardboard Boxing a RefineryPlus crashes you to desktop

### ISSUE THREAD

**Issue by Sovereignty89** [TPPIDev/TestPackPleaseIgnore2#163]
http://pastebin.com/rTEE9uPx this log will be created after you try and remove the cardboard box from the RefineryPlus and you ctd. 

Trying to get back in to the game will cause you to ctd, it needs to be edited out if this occurs.

Thank you Prof!

**Comment by HaroldDaFrog** [comment]
Does not crash in single player, guessing we'll just need to adjust the blacklist for the sake of servers.

**Comment by TehNut** [comment]
Once we get Mek forked, this will be fixed. I'll look into it when I get a chance.

**Comment by TehNut** [comment]
Actually, I can't even crash it on the server. Neither can Reality.
