### ISSUE TITLE
Monazite should spawn in the overworld

### ISSUE THREAD

**Issue by Sovereignty89** [TPPIDev/TestPackPleaseIgnore2#167]
This was oversight on my part, Monazite should spawn in the overworld. 

Monazite can be processed down to get Neodymium, a material that is needed in a lot of crafting above High Voltage(512EU/t) in GT. 
Monazite usually spawns in the overworld but this was obviously turned off. It does not spawn in the Nether nor the End, neither does Neodymium, Forcicium, Bastnasite and Forcillium, the latter 3 being ores that you can process to get Neodymium as well.

http://puu.sh/eFkuz.png
http://puu.sh/eFmPx.png
http://puu.sh/eFnuP.png

You can see in the picture above that the main ore is Bastnasite with sporadic Monazite ore.
But you get about 0.22 Neodymium Dust from 1 Bastnasite Ore, requiring a lot more in the world-gen.
You can get about 1.77 Neodymium Dust from 1 Monazite Ore if processed properly. So I suggest Monazite, relatively rare.

http://puu.sh/eFlBT.png 
That is the amount of customthings ores I have, if I could make a suggestion, maybe as rare as stibnite(3478), maybe even lower? The lowest number in there is Iridium(664).

**Comment by esKaayY** [comment]
@TehNut I needs texture, then I'll json it

**Comment by tjsd** [comment]
if its only the icon file from customthings folder I made one:
http://i.imgur.com/QYui0Wd.png
