### ISSUE TITLE
Wither Skeletons can Become Infernal

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#168]
...when spawned from an enderio powered spawner. From what I can tell, they don't have this problem anywhere else. This does not seem to happen with other hostile mobs when spawned in such a way.

**Comment by tterrag1098** [comment]
With the latest EIO wither skeletons are their own mob, completely separate. We'll need to add the respective line to the infernal mobs config.
