### ISSUE TITLE
QuarryPlus Duplication of Land Marks. 

### ISSUE THREAD

**Issue by reality404** [TPPIDev/TestPackPleaseIgnore2#171]
I placed down 3 Land Marks and right clicked them to set them.
I then placed a QuarryPlus next to a Land Mark but it did not select the border set by the Land Marks.
I broke the QuarryPlus and replaced it down and it still did not select the border set by the Land Marks.
I logged out and re logged in.
When I logged in I noticed that the landmarks where broken and instead of getting 3 back I got 6 back. I logged out and re logged to confirm that the landmarks had duplicated and placed them down to make sure that they where real.

**Comment by HaroldDaFrog** [comment]
I played around with this putting down things in all sorts of combinations with both regular landmarks and the ones from q+, can't seem to replicate it. Must have been a one off thing.

**Comment by MikeLydeamore** [comment]
I too have had no issues with landmarks and QuarryPlus

**Comment by reality404** [comment]
Thanks HaroldDaFrog and MikeLydeamore. I have tried to replicate the bug in single player and multiplayer but I can't seem to. It must have been a one time issue.

**Comment by TehNut** [comment]
Closing until it is replicated.
