### ISSUE TITLE
ME Sorting Interface causes client to crash.

### ISSUE THREAD

**Issue by Rapthera** [TPPIDev/TestPackPleaseIgnore2#173]
Doesn't matter what I do, just by placing it in the world causes it to crash in SP.

Have not tried in SMP yet.

It belongs to Refined Relocation

http://pastebin.com/raw.php?i=vxdiGkWZ

I suppose it doesn't help having refined relocation have a dependency of ae build beta1 >.>

**Comment by esKaayY** [comment]
Should be fixed with an update to Refined Relocation 1.0.7d

**Comment by Rapthera** [comment]
Update to Refined Relocation 1.0.7.d fixed the issue.
