### ISSUE TITLE
spawn ratio of bee hives

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#174]
while exploring the world looking for hives I have found that there is an extrem ammount of magical bee hives and normal forestry bee hives is almost not to be found. Seems the ratio is off by alot. I find 4-5 resonating hives before I find 1 meadows hive.

**Comment by FakoTheGreat** [comment]
Considering the age of the current map (and the addition of Binnie's to the mix later on in its cycle), we'll likely need to do some SSP creative mode checks to see if that ratio is still off.  Definitely a concern.

**Comment by HaroldDaFrog** [comment]
Rapthera and I can both confirm this

**Comment by Iwerks** [comment]
http://www.reddit.com/r/feedthebeast/comments/2tuwmo/cant_find_regular_forestry_bee_hives/

Relevant. Other people have the same issue with other packs.

**Comment by Iwerks** [comment]
Latest Forestry update may fix this issue.

http://www.reddit.com/r/feedthebeast/comments/2u686u/forestry_340s_big_release/

**Comment by esKaayY** [comment]
Fixed with latest update
