### ISSUE TITLE
botania - balance with thermalillies

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#175]
To use them (they are now elven knowledge) you have to place lava on obsidian. Meaning you would need to use a buildcraft filler. This disables the use of serenade of the nether from blood magic. Forcing people to keep pumping the nether dry, instead of being able to use life points.
I suggest  you set this option to false on the server:

    # Set to true to only allow the Thermalily to absorb Lava if there's Obsidian below it. Another config option for the Blood Magic balance freaks.
    B:thermalily.obsidian=false

In the client config it is false.

**Comment by TehNut** [comment]
I'd much prefer to keep this true.

**Comment by Rapthera** [comment]
If you're THAT keen on using the BM ritual you can just set that up to fill the drum which then gets pulled into the flood gate.

**Comment by tjsd** [comment]
I must disagree. You can only get lava from a serenade of the nether with a tier 3 altar and setup for constant supply of blood. Putting it at endgame stage. 

As it is now you encourage people to go pump the nether dry to power the thermalillies. And since enderthermic pump requires a bit of resources people might use buildcraft pumps causing lag. 

If anything moving to botania should be encouraged, since it is preventing lag. I am very curious about your reasoning behind wanting to leave it disabled.

**Comment by tterrag1098** [comment]
@Iwerks has already proven that it is completely possible to get to tier 3
within a few hours of gameplay.

**Comment by tjsd** [comment]
you still need to open the portal to alfheim to get thermalillies

**Comment by tjsd** [comment]
@tterrag1098 and so? is it negative to use the ritual compared to a buildcraft pump in nether? I dont understand.

**Comment by Rapthera** [comment]
Tier 3 altar is NOT endgame, you can reach tier 3 after circa 30 minutes of continuous playing, early-midgame at most.

If you really want to use your Serenade of the Nether for Thermalilies you can feed the lava generated by them directly into the flood gate.

**Comment by tjsd** [comment]
I can get a bc pump in the nether after 15 minutes of play.

**Comment by TehNut** [comment]
Pumping lava requires some infrastructure. Going straight from the ritual requires absolutely nothing. Config is staying how it currently is.
