### ISSUE TITLE
Downgrade GT one version 

### ISSUE THREAD

**Issue by Sovereignty89** [TPPIDev/TestPackPleaseIgnore2#176]
Please downgrade GregTech one version to 5.07.06.
As seen http://puu.sh/ePdrP.png there is a problem creating blocks and plates out of certain gems with GT. All block versions of gems have been removed by GT, not sure why, maybe in preparation for something to come.
We can't create many of the gem blocks which need to be cut in to plates in order to make lenses out of them so they can be used for circuit creation.

I was hoping we could downgrade GT one version so we can maybe act like we can continue up the tech tree? (Hint Hint Monazite)

BoP blocks are not accepted by the cutting machines to turn in to plates.

**Comment by esKaayY** [comment]
Closed with latest "update"
