### ISSUE TITLE
Client crash while looking up uses for Uranium ore

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#177]
So I was running around in a singleplayer world to test stuff, and hit U on a uranium ore to check if I could grind it to yellorium and the client crashed.

Crash Log: http://pastebin.com/jMeJRkJe

**Comment by Cyrakrum** [comment]
Tried last night, was able to view uranium processing.

**Comment by TehNut** [comment]
Works just fine. All pages.
