### ISSUE TITLE
Mekanism Circuits require GT

### ISSUE THREAD

**Issue by MikeLydeamore** [TPPIDev/TestPackPleaseIgnore2#185]
Not sure if intended or not, but the Basic Circuit can be made the normal way, while the Advanced and Elite circuit require the GT Assembler.
This is obviously nice for buffing the cost of the Digital Miner, but a bit of a pain for setting up the lower tiers of Mek ore processing.

**Comment by Sovereignty89** [comment]
There is already an issue about this https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/92.
