### ISSUE TITLE
Single block of Bedrock at y2 with a non removable water source on top.

### ISSUE THREAD

**Issue by reality404** [TPPIDev/TestPackPleaseIgnore2#186]
I found a single block of Bedrock at y2 with a non removable water source block on top https://imgur.com/isZ6cjn. I have tried reloging and placing blocks on top of the water source but when I remove the block placed on top the water source comes back. I have also tied using  a vanilla bucket I'm able to pick up the water source but within a couple of seconds the water source comes back. I have also tried a extrapolated bucket it removes the water source but it comes back again after a couple seconds.

**Comment by Iwerks** [comment]
This has been around since forever. I cannot remember if its Buildcraft or Railcraft that does this.

**Comment by tterrag1098** [comment]
Intended feature of buildcraft

**Comment by reality404** [comment]
Thanks Iwerks and tterrag1098. Sorry for reporting issue I did know it was a intended feature of buildcraft.
