### ISSUE TITLE
[Pneumaticcraft] Pressure Chamber Chunk Loading

### ISSUE THREAD

**Issue by Cyrakrum** [TPPIDev/TestPackPleaseIgnore2#191]
If a pressure chamber becomes unloaded and then reloaded it seems to leak pressure until you reform the structure (The pressure noise can clearly be heard and nothing will craft)

**Comment by c1ph3r88** [comment]
If it helps, this is a known issue with PneumaticCraft.

https://github.com/MineMaarten/PneumaticCraft/issues/388#issuecomment-73324753

**Comment by TehNut** [comment]
Invalid because the mod is no longer with us.
