### ISSUE TITLE
[Bug] Mekanism 5x can skip 4x and 3x step in Ore Processing

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#193]
In 5x you use a chemical dissolution chamber that makes gold slurry, that goes into a chemical crystalizer and produces Gold Crytal (for instance).

This crystal is supposed to then go trough the enitire 4x process with brine, then 2x and so on.

But you can put the crystal straight into a pulverizer, rock crusher or macerator to get gold dust. Circumventing the entire chain.

**Comment by tjsd** [comment]
It doesn't stop there. You can take any of the steps and use different machines to get secondary outputs as well. Its a broken mess :(

**Comment by Sovereignty89** [comment]
This is known and it's caused by Factorization and AOBD and probably even GT. It's an unfortunate side-effect of all these mods interacting with each other
