### ISSUE TITLE
[Multiple Mod Conflict] World Unifcation By Greg

### ISSUE THREAD

**Issue by Cyrakrum** [TPPIDev/TestPackPleaseIgnore2#194]
Rapthera pointed out to me that we don't have bug reports for some of the world unification from greg... So I thought we should make one thread to put them all in... If anyone finds an item that when dropped into the world unifies into another (Because this should not be happening with anything. It's why we have fucking unifiers and sorting importers and jabba barrels) post it here (preferably with the oredict value because maybe that'll be helpful? Oh and the mod it's from)

I'm also going to note that while the world unification is definitely from GregTech and doesn't have an off config, some of the actual world unifications are not caused by greg.

Forbidden Magic Nether shards ForbiddenMagic:NetherShard

Ink Sacs to Bone meal minecraft:dye (Worth noting that this interaction doesn't happen with gregtech alone, it's some sort of mod interaction. Also this doesn't happen with any other minecraft:dye items)

Gregtech Apatite to Forestry Apatite gregtech:gt.metaitem.01 to Forestry:apatite (Seems it's not based on ore dictionary...)

**Comment by TehNut** [comment]
But.. We do have reports for this already. #169 for example.

**Comment by stardustrider** [comment]
I found that the Ink Sac to Bonemeal was an issue with Tinkers Steelworks. Removing the mod fixes it.
