### ISSUE TITLE
ME Conduits + Energy Conduits crash the game if placed in one block.

### ISSUE THREAD

**Issue by TwiiCe** [TPPIDev/TestPackPleaseIgnore2#196]
I love the new textures, but when you place an ME conduit (That was already hooked on to a live ME system) in the same block as an advanced energy conduit (havent tested with others) your game crashes. 

I have a full log on pasteee http://paste.ee/p/FwsTp

The error occured at line: 46767 (This is the point where I attempted to place the conduit)

**Comment by tjsd** [comment]
This has been fixed in latest ender io build.

**Comment by tterrag1098** [comment]
Confirmed

**Comment by esKaayY** [comment]
Fixed with update to EnderIO
