### ISSUE TITLE
[Suggestion] Add MoarPeripherals

### ISSUE THREAD

**Issue by KingofGamesYami** [TPPIDev/TestPackPleaseIgnore2#20]
[Github](https://github.com/theoriginalbit/MoarPeripherals)
[ComputerCraft Forums](http://www.computercraft.info/forums2/index.php?/topic/19357-mc-1641710cc-163164-moarperipherals/)

Adds more peripherals for computercraft, and the author, @theoriginalbit, accepts ideas from the computercraft community.

Most of the mod is configurable, which makes it easy to fix any incompatibilities, and I'm sure the author would be willing to fix things on his end as well.

**Comment by TehNut** [comment]
No Computercraft anymore.

**Comment by KingofGamesYami** [comment]
Can I ask why CC was removed? :sob: :sob:

**Comment by TehNut** [comment]
It was removed months ago lol. OpenComputers is the replacement.
