### ISSUE TITLE
Golden Chipset recipe incorrect

### ISSUE THREAD

**Issue by jaxory** [TPPIDev/TestPackPleaseIgnore2#203]
Golden chipset is requiring 16 gold ingots+1 redstone for 1 golden chipset. Recipe should only be 1 gold ingot and 1 redstone at the assembly table to create it, similiar to the iron and diamond chipsets.

**Comment by tterrag1098** [comment]
See https://github.com/CrazyPants/EnderIO/issues/1942

**Comment by TehNut** [comment]
Fixed in https://github.com/CrazyPants/EnderIO/commit/fa4e0c360c3b2e2bd6edeaf094d95c9f629dc0d8
