### ISSUE TITLE
EIO Capacitor Banks Derping when Blown Up

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#204]
When an Enderio capacitor bank of any tier is blown up by an explosion of any sort, it will change the capacitor bank to a "Creative Capacitor Bank" in name only. However, if there is any power in the original bank at all, then the amount in the "Creative Capacitor Bank" will be set to 5m rf, that drains out as normal. So basically, this allows you to upgrade the basic capacitor banks to normal ones, and to get up to 4,999,999 rf for free. Results may vary. 
To reproduce, simply blow up a capacitor bank with some power in it with TNT. This is in version 2.2.8.350 of enderio.

**Comment by FakoTheGreat** [comment]
In personal testing of this issue, I can get the bank's metadata to change, but the other values (such as energy stored, max energy throughput, and max capacity) remain unchanged.

**Comment by Cyrakrum** [comment]
Oh right reality404 also had that happen to our banks.

**Comment by TehNut** [comment]
Known here https://github.com/CrazyPants/EnderIO/issues/1991

**Comment by MikeLydeamore** [comment]
This has been fixed in EnderIO Build 354.
