### ISSUE TITLE
Client crash - placing mfr harvester

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#205]
So, if you break a harvester with a pickaxe, it doesnt stack with other harvester anymore. Placing down one of the broken ones causes a instant client crash.

I used a dark steel pickaxe with silktouch enchant and spoon upgrade to break it. You cant pick it up with ender io yeta wrench,

http://pastebin.com/zH6z46CH

**Comment by TehNut** [comment]
Try with a different pickaxe. It might be an EnderIO derp.

**Comment by tjsd** [comment]
https://github.com/skyboy/MineFactoryReloaded/issues/376 <

**Comment by esKaayY** [comment]
Fixed with latest update.
