### ISSUE TITLE
Wither skeletons drop necrotic bones 100% of the time.

### ISSUE THREAD

**Issue by TheSomnambulist** [TPPIDev/TestPackPleaseIgnore2#206]
This works in singleplayer, as well as the multiplayer server.  Looting does not affect the outcome, and they are still capped at a maximum of one necrotic bone per skeleton.

**Comment by HaroldDaFrog** [comment]
This smells like an Enderio derp up, I would report it over there as well.

**Comment by TehNut** [comment]
Fixed at some point.
