### ISSUE TITLE
KitchenCraft - New Dragonburger 

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#207]
The Patty lists itemSalt as valid component, but it does not accept mekanism salt. That is itemSalt in oredict.

**Comment by FakoTheGreat** [comment]
That was a failing point on my part. While the salt added in KitchenCraft was properly oreDicted, I didn't use the oreDict entry when creating the recipe.  Will be fixed as of the next commit I push.

**Comment by TehNut** [comment]
Fixed in a recent commit.
