### ISSUE TITLE
Petal Apothecary munching empty buckets

### ISSUE THREAD

**Issue by MikeLydeamore** [TPPIDev/TestPackPleaseIgnore2#209]
Seems as though right-clicking the petal apothecary (with no water in it) with an empty bucket causes the bucket to vanish.
Both shift right clicking and breaking the apothecary don't get it back.

Reported to Botania GitHub also:
https://github.com/Vazkii/Botania/issues/594

**Comment by TehNut** [comment]
Fixed in next Botania build.

**Comment by esKaayY** [comment]
Need to update to Build 164 or later. Currently on 163

**Comment by Rapthera** [comment]
No longer a issue.

**Comment by TehNut** [comment]
Oh did we update?

**Comment by FakoTheGreat** [comment]
We're past build 164 now. Closing issue until I hear it's still happening.
