### ISSUE TITLE
Client Crash to Desktop From Lumber Axe & Carpenter's Garage Door

### ISSUE THREAD

**Issue by FakoTheGreat** [TPPIDev/TestPackPleaseIgnore2#21]
As the title says, breaking a carpenter's garage door using a lumber axe can cause a crash to desktop for the client (server doesn't crash, but see below).

I was able to recreate the bug by building a doorway that was three blocks wide and tall, then placing three carpenter's garage doors along the top (they fill to the bottom). I then broke the middle block with a lumber axe to generate the following crash report: http://pastebin.com/1uusgDAb

It is worth noting that the middle and left doors were correctly broken (and dropped as normal), but the right door was not broken.  All broken blocks correctly dropped.

**Comment by TehNut** [comment]
Fixed at some point.
