### ISSUE TITLE
Crash on creating golem bell

### ISSUE THREAD

**Issue by Cyrakrum** [TPPIDev/TestPackPleaseIgnore2#212]
Crashed twice when creating the golem bell from thaumcraft. When I moused over the item it said null. 

http://pastebin.com/K4JcGG6E

**Comment by FakoTheGreat** [comment]
The source of this issue is apparently Thaumic Horizons, which replaces the bell to allow the animated golems to function.  We can't work around the adjustment, so the add-on will likely need to be shelved for initial release.

**Comment by esKaayY** [comment]
Temporarily solved by removing thaumic horizons for open beta. Still an issue.

**Comment by TehNut** [comment]
Closing as it doesn't seem we will be re-adding TH anytime soon.
