### ISSUE TITLE
Server Crash with Modular Armor

### ISSUE THREAD

**Issue by MikeLydeamore** [TPPIDev/TestPackPleaseIgnore2#213]
I'm pretty sure this is because Zombie's don't have configs...
Caused a recurring server crash: http://puu.sh/ghOrO/7f232e41de.txt

**Comment by tjsd** [comment]
Yeah I get the same on my local instance, try to access the armor config and it reboots the server instantly.

http://paste.ubuntu.com/10507264/

**Comment by chbachman** [comment]
Fixed in Dev. I derped up on some Util Methods. Sorry :)

**Comment by FakoTheGreat** [comment]
Update was applied in latest alpha and the crash hasn't reared its ugly head again as of late. Calling this one closed... for now.
