### ISSUE TITLE
Expensive crafting recipe for soul fragments still diminishes max health.

### ISSUE THREAD

**Issue by thevirtualgamer** [TPPIDev/TestPackPleaseIgnore2#217]
Crafting an Extra Utilities soul fragment with the alternate, expensive recipe (the one that takes 4 green hearts, 4 nether stars, 1 dragon egg/galgadorian block) still diminishes 10% of your health bar once you take the soul fragment out of the crafting table.

**Comment by FakoTheGreat** [comment]
He's watching when one is crafted by any means, meaning that I sadly don't know how to solve this easily.  However, if the crafting is done via non-conventional means (such as a cyclic assembler or auto workbench), then the health isn't lost.  I'll add a tooltip to the soul on the next build of TPPI-Tweaks to let people know of this.

**Comment by FakoTheGreat** [comment]
The next build of TPPI-Tweaks contains said tooltip.
