### ISSUE TITLE
[suggestion] spawn eggs for ocelots & wolves

### ISSUE THREAD

**Issue by highlander777** [TPPIDev/TestPackPleaseIgnore2#218]
so for witchery and thaumcraft you will some times need a dog or a cat and thanks to biomes of plenty they are nearly impossible to find i personalty have spent 8+ hours walking around a jungle biome looking for ocelots so i suggest a recipe for a spawn egg for ocelots and wolves

Ocelots:  have a 1 use safari net in the center and 1 fish in each corner

wolves: have a 1 use safari net in the center and 1 bone in each corner 

this would allow player to be able to advance in thaumic horizons and witchery and use the mod to its fullest with out having to search for days for a simple animal

**Comment by FakoTheGreat** [comment]
Taken care of in the next build.
