### ISSUE TITLE
Mod Tweaker

### ISSUE THREAD

**Issue by bookerthegeek** [TPPIDev/TestPackPleaseIgnore2#223]
I und we understand that minetweaker is added solely for server owners, and that you. Sadly it does not cover many modded recipes. 

Adding "mod tweaker" would allow server owners to better utilize mine tweaker as it will open up many more modded recipes for modification to server owners AND should not pose any additional issue here because as stated mine tweaker, and hopefully mod tweaker, would be added solely for servers and not be use in the recommended release of tppi2

**Comment by FakoTheGreat** [comment]
ModTweaker was in the early builds of TPPI2, but we found that (back then) the handler it had for Mekanism Gas would cause a crash the instant it was handed any script to use, no matter what was being altered. That no longer appears to be the case, so it'll be making a comeback.  Thank you for the reminder.

**Comment by bookerthegeek** [comment]
Your welcome,  and rthank you for the amazing mod pack
