### ISSUE TITLE
Dense Ores & Alloy Smeltery yields 1 ingot for each dense ore.

### ISSUE THREAD

**Issue by Rapthera** [TPPIDev/TestPackPleaseIgnore2#224]
As title states, currently smelting a dense ore in a alloy smelter yields 1 ingot, this also applies to ALL Dense ores.

**Comment by FakoTheGreat** [comment]
Will have to see if the configs for custom alloy smelter recipes will allow for dense ores to provide triple output in the alloy smelter as intended. If not, not much that can be done about this.
