### ISSUE TITLE
Eira Enabled By Default - Should be disabled by default

### ISSUE THREAD

**Issue by esKaayY** [TPPIDev/TestPackPleaseIgnore2#234]
Autojoin is on. Should be off by default. Need to confirm what the gui does.

**Comment by tterrag1098** [comment]
Last time around we left it enabled by default until the pack was public,
no?

**Comment by TehNut** [comment]
@tterrag1098 It was enabled by default until we had complaints that it should be opt-in. That's why it was changed to disabled by default.

It *should* be disabled by default.

**Comment by tterrag1098** [comment]
@TehNut That is definitely not what happened. We decided against disabling it beta because of the relatively small user base. Once it went public we figured it best to change that due to the large influx of new players.
