### ISSUE TITLE
Issue at end of startup.

### ISSUE THREAD

**Issue by Sayshal** [TPPIDev/TestPackPleaseIgnore2#237]
So, once I finally get to the menu, haven't clicked any buttons or anything, I noticed in the FTB Console I was getting spammed. 
Steps to Reproduce:
1. Launch game on latest beta (0.1.1)
2. Watch console for when you're finally at the main menu.
3. Don't touch any buttons, watch console explode (https://gist.github.com/Sayshal/0e37a93924f5c04ebce0)

Normally, I'd shrug because console spam is normal, but I'm noticing the javaw.exe (ftb console process, I've checked) is sucking my CPU dry, usually hovering at 30-50% CPU usage on an i5-4690k. Just wondering if this is my fault or a beta bug.

**Comment by TehNut** [comment]
It's an issue with Xaero's minimap. We've reported it already.

**Comment by TehNut** [comment]
Closed by 77b4d3e92cf27c4cc9499ef3ed34756d97248212
