### ISSUE TITLE
Disable Nether Iridium Ore

### ISSUE THREAD

**Issue by TehNut** [TPPIDev/TestPackPleaseIgnore2#238]
Breaks "vanilla" IC2 progression. It's meant to be created, not found.

Y/N?

**Comment by FakoTheGreat** [comment]
Actually, it's meant to be found, but in dungeon loot and such. I vote to disable the nether iridium.

**Comment by TehNut** [comment]
Right

**Comment by downslope7** [comment]
I think this is a good idea to do. Totally messes up IC2 late game IMHO.
