### ISSUE TITLE
Quarry Recipe Not Working

### ISSUE THREAD

**Issue by Aubron** [TPPIDev/TestPackPleaseIgnore2#239]
Not sure if this is something unintelligent I'm doing or not, but no matter what I do I cannot craft the BC Factory Quarry.

Recipe Given:
http://i.imgur.com/V9cl8YE.png

Recipe Used:
http://i.imgur.com/R8LwR9M.png

Exact same, but the diamond drill is not max durability (because this item is not obtainable, given the charge nature of the drill)

**Comment by TehNut** [comment]
IC2 bug. We'll look into it.

**Comment by tterrag1098** [comment]
Fixed via https://github.com/TPPIDev/TPPI-Tweaks/commit/ce161a0f8f88c6cea879f46222fa796fb0ffe25e
