### ISSUE TITLE
Edit tooltips on compressed diamond and compressed obsidian to indicate recipe removal was intentional (if they remain removed)

### ISSUE THREAD

**Issue by downslope7** [TPPIDev/TestPackPleaseIgnore2#240]
In the mek enrichment chamber. Makes for less efficient use of the materials in the infusers.

Also, you can't make portable teleporters without compressed obsidian.

**Comment by downslope7** [comment]
I take back the part about the portable teleporters. You still lose out on efficiency though.

**Comment by FakoTheGreat** [comment]
The removal of compressed diamond and obsidian is intentional, as their removal increased the cost of mekanism teleportation, both personal and mining-wise.

**Comment by downslope7** [comment]
Updated issue title per discussion on IRC.
