### ISSUE TITLE
Opis(Map Writer) config not persisting

### ISSUE THREAD

**Issue by mrgreenacid** [TPPIDev/TestPackPleaseIgnore2#246]
I removed xaeros(sic?) map and replaced with included opis. Way points and setting changes like draw distance/texture size/draw coords do not persist when game is closed and re-opened.

**Comment by TehNut** [comment]
Does your game have write access to the directory?

**Comment by mrgreenacid** [comment]
Something didn't have permission to write, chmod 777 whole folder because I am lazy, it works now.  Still getting used to linux.  Thanks
