### ISSUE TITLE
Iron Turning Table

### ISSUE THREAD

**Issue by mrgreenacid** [TPPIDev/TestPackPleaseIgnore2#252]
Turning table has no recipe.  I found a recipe online that worked properly [iron][iron item casing][iron], I was making it for my diamond drill for a quarry, I put it in an AE system and now I cannot remove it.  Have tested on 2 worlds Ubuntu 14.04 and windows 7.

Edit: It appears that taking the 1K storage cell out of the ME drive and replacing it allows me to remove the item once.

**Comment by TehNut** [comment]
I see a recipe.

![Recipe](http://tehnut.info/share/RjHxHxTfq.png)

**Comment by mrgreenacid** [comment]
Wow my bad, I meant to say iron turning blank...man I am bad at these bug reports.

**Comment by AjwBoss** [comment]
Iron turning blank has a recipe, it just doesn't show in the nei.  Two iron ingots around iron item casing.
ICI

**Comment by mrgreenacid** [comment]
I said that in my original post....The problem is that it gets stuck in ME systems.
