### ISSUE TITLE
TPPI2 Repeating Biome 

### ISSUE THREAD

**Issue by Auxion** [TPPIDev/TestPackPleaseIgnore2#254]
I'm playing tppi2, I started on default world. I've travelled thousands of blocks in all directions and there only seems to be 2/3 biome types (extreme hills/mushroom island/sometimes some water) it feels like a huge biomes checkered mystcraft world.
Has anyone else encountered something similar?

Not sure if all these version are relevant but better safe than..

Versions:
Minecraft 1.7.1
MCP 9.05
FML 7.10.85.1291
Forge 10.13.2.1291
TPPI2 Beta 0.1.0

**Comment by TehNut** [comment]
Latest TPPI2 version is `0.1.1`, not `0.1.0`.

Can you replicate in new worlds?

**Comment by Auxion** [comment]
I had 1.1 selected in the launcher, but the main menu in game says 0.1.0

**Comment by FakoTheGreat** [comment]
We experienced a similar issue using "Default" world type.  You'll want to change to "Biomes O' Plenty" before loading up a new world, at least for now.

**Comment by Auxion** [comment]
ok, thanks very much, for the modpack also :)
