### ISSUE TITLE
Client Crashes to desktop

### ISSUE THREAD

**Issue by whomightub** [TPPIDev/TestPackPleaseIgnore2#261]
Players were on the server yesterday. No changes since then. Today, the server is inaccessible from the client. Client crashes to desktop when accessing the server.  Deleted and re-downloaded the client and server for TPPI2 0.1.1, problem persisted. Caught this image once:
http://www.orekingdom.com/forum/m/22828153/viewthread/20815164-tilewhitesnow-on-tppi2-server/post/last

**Comment by TehNut** [comment]
http://www.reddit.com/r/TestPackPleaseIgnore/comments/310tpz/cant_connect_due_to_tilewhitestone_microblock_is/
