### ISSUE TITLE
[SOLVED] Entity is already tracked! console spam

### ISSUE THREAD

**Issue by brbrainerd** [TPPIDev/TestPackPleaseIgnore2#262]
My console was getting spammed with the following errors:

java.lang.IllegalStateException: Entity is already tracked! 
thread/ERROR]: "Silently" catching entity tracking error. 
entity to track

These errors started showing up after one of my users placed an ender-thermic pump in the nether.  This is a known issue: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/161#issuecomment-72996794 and http://www.minecraftforge.net/forum/index.php?topic=28183.0

I was able to fix the issue by changing line 821 of EnderIO.cfg in version 0.1.1 of TPPI2:

replacewitherskeletons {
    # Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]
    B:Misc=true
}

Changing B:Misc=true to false fixes the issue.  I would recommend including this change in future releases.  

Thanks for the awesome modpack!

-brbrainerd

**Comment by TehNut** [comment]
Closed in f6f5170753de7f45cc5aef7aff7c347df596b505
