### ISSUE TITLE
Massive CPU Lag - Requiring restart

### ISSUE THREAD

**Issue by Sayshal** [TPPIDev/TestPackPleaseIgnore2#263]
I think I've narrowed down the cause of the CPU Lag myself, and others have reported:
http://www.reddit.com/r/TestPackPleaseIgnore/comments/318sse/first_impressions_of_tppi2/cpzf682
http://www.reddit.com/r/TestPackPleaseIgnore/comments/318sse/first_impressions_of_tppi2/cpzfn4t

It seems to happen after opening my inventory, and I'm seeing this in my console: http://puu.sh/h0Fdo.png

Hopefully this will help narrowing down the cause.

As for reproducing, have stuff in your inventory and play the game, if you open it and suddenly get 0-1FPS and 100% CPU usage, check your console for similar errors! I'll post more if I get different errors, etc.

**Comment by TehNut** [comment]
Fixed in 7ac2ed7892ed78daa4659cc9c7f9e9d8360a3dcb
