### ISSUE TITLE
Add MinecraftLoader to the pack

### ISSUE THREAD

**Issue by Gaelan** [TPPIDev/TestPackPleaseIgnore2#266]
MinecraftLoader is an insanely useful mod for large packs that adds a progress bar to the Mojang screen.
Modpack policy:
> You are free to use this mod in a modpack after you have send me a [pm]  :) .

[MCF Link](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091925-minecraftloader-v0-1-3-improved-loading-screen)

**Comment by TehNut** [comment]
We had it, it caused a *major* memory leak that rendered the game unplayable afterwards, decided to stay away from it.

No.

**Comment by Gaelan** [comment]
Oh, ok. Also, that is one quick response.
