### ISSUE TITLE
Iron Chest Crash

### ISSUE THREAD

**Issue by Unknown-404** [TPPIDev/TestPackPleaseIgnore2#268]
Game crashes whenever I open an iron chest. Haven't tried it with other upgraded chest types

**Comment by tterrag1098** [comment]
Log.

**Comment by Unknown-404** [comment]
http://pastebin.com/UjGtEFZt

**Comment by TehNut** [comment]
Is it reproduce-able with other chests of the same type?

**Comment by Unknown-404** [comment]
Empty iron chest also crashed. I'm going to try a gold chest once the game launches... takes a long time on this pc

**Comment by TehNut** [comment]
Have you made any changes to the pack?

**Comment by Unknown-404** [comment]
All of the changes I've made were also made by Sayshal on his client and he isn't crashing when he opens iron chests.

-Using Sphax 32x with patches (Assembled by Sayshal)
-Enabled Opis-1.3.0_dev12.1.7.10
-Disabled xaeros_minimap_v1.3.7.4_1.7.10_Forge

**Comment by TehNut** [comment]
Can you try a fresh install the pack?

**Comment by Unknown-404** [comment]
It was the resource pack... idk why it was only doing it to me.
