### ISSUE TITLE
Sanguimancy-related crash

### ISSUE THREAD

**Issue by DimpleBeard** [TPPIDev/TestPackPleaseIgnore2#278]
I created myself a corrupted blade and tried right-clicking with it, thinking that I would bind it to myself, and the server simply crashed. Shift-right-clicking also causes the same crash. Corrupted pickaxe does the same thing, presumably the other corrupted tools do as well.
Crash log: http://paste.ubuntu.com/10782681/

As a side note, I'm not sure if maybe this is happening because my soul corruption is so low that the items are trying to change their function and are finding a null value or something? Just a thought.

**Comment by DimpleBeard** [comment]
Note: Shift-right-clicking also causes the same crash.

**Comment by Tombenpotter** [comment]
One main thing to say. @tterrag1098 y u no update m8.
For the story, this was caused by a change in the BM API. New Sanguimancy versions are good with it.
