### ISSUE TITLE
Items placed in Blood Altar only render on one side

### ISSUE THREAD

**Issue by WhitePhoenix0** [TPPIDev/TestPackPleaseIgnore2#281]
Blocks are fine, but if you place an item on the altar, its invisible half the time because the side towards you is not rendering.

imgur.com/AzVptwo
imgur.com/gvZsWG1

**Comment by TehNut** [comment]
Use Fancy Graphics.

**Comment by tterrag1098** [comment]
This is still a bug.

**Comment by TehNut** [comment]
How is it a bug? It's how Blood Magic renders it.

**Comment by tterrag1098** [comment]
Renders it *in a bugged way*

**Comment by tterrag1098** [comment]
I'm fixing it with way now.
