### ISSUE TITLE
Potions missing recipes in NEI

### ISSUE THREAD

**Issue by Huene** [TPPIDev/TestPackPleaseIgnore2#282]
Vanilla potions seem to be missing their recipes in NEI

**Comment by TehNut** [comment]
https://github.com/TPPIDev/TestPackPleaseIgnore2/blob/Development/config/INpureProjects/custom_nei_filters/vanilla.js#L7

**Comment by tterrag1098** [comment]
I would argue that it's mostly pointless to hide potions in NEI. Why was that done?
