### ISSUE TITLE
Commands on server not working

### ISSUE THREAD

**Issue by plato2000** [TPPIDev/TestPackPleaseIgnore2#284]
On a server, ServerTools blocks some commands by a non-op that shouldn't be blocked. For example, /ores is blocked.

**Comment by TehNut** [comment]
Then... Add them to the permissions list? This isn't really our issue.

**Comment by tterrag1098** [comment]
Well, we should probably whitelist those commands by default.

**Comment by TehNut** [comment]
Fixed in TPPIDev/TPPI-Tweaks@957756ea5e1acaed9fba921f7549766468b2329e
