### ISSUE TITLE
Teleporting to minimap waypoints is enabled

### ISSUE THREAD

**Issue by WhitePhoenix0** [TPPIDev/TestPackPleaseIgnore2#287]
https://www.youtube.com/watch?feature=player_detailpage&v=gnL2-5aDqq4#t=168

I was watching this tppi2 video, and at this time he mentions that is has been enabled, and teleports down to his mine.

**Comment by TehNut** [comment]
It is enabled if cheats are enabled. Or if you have OP on your server.

**Comment by NetMasterFlex** [comment]
I'm sorry but can someone link me to instructions for finding the client via FTB launcher. I'm unable to find it. I can get the server from github I think right?  I would like to test as well

Amador

**Comment by TehNut** [comment]
That had absolutely nothing to do with this issue. Please learn what Google is.
