### ISSUE TITLE
Clicking statistics crashes the game

### ISSUE THREAD

**Issue by WhitePhoenix0** [TPPIDev/TestPackPleaseIgnore2#288]
Log from logs folder: http://pastebin.com/ftcAN6fR

Crash Report: http://pastebin.com/HrBtM1NL

I simply click statistics, it says shutting down server... then its gone.

**Comment by TehNut** [comment]
Your logs have provided me with [technical kitty cats](http://tehnut.info/share/aVGHbn1oT.png). I am happy. 

I have noticed this as well actually. Been meaning to go through and see which mod is breaking it.

**Comment by chylex** [comment]
It's probably me, in which case you have a seriously outdated version of HEE. 1.7.1 or newer fixes it.
