### ISSUE TITLE
[0.1.4] [Cauldron] Mystcraft "dummy" dimension -2147483648 makes cauldron explode

### ISSUE THREAD

**Issue by stevestech** [TPPIDev/TestPackPleaseIgnore2#299]
It seems that with the new version of MystCraft, a dummy dimension named DIM_MYST-2147483648 is generated for profiling purposes. For some reason this causes a crash on start-up when used with Cauldron.

Cauldron version: 1.7.10-1.1388.1.0
Crash log:
http://paste.ubuntu.com/10921216/
Sometimes I get this one instead: 
http://paste.ubuntu.com/10921279/

**Comment by stevestech** [comment]
When I disable the mystdummy dimension in cauldron.yml, this crash log is produced:
http://paste.ubuntu.com/10921310/

**Comment by Sayshal** [comment]
I am experiencing the same problem with Mystcraft 11.5

Some things I'm trying that you should try to see if we have similar problems:
Downgrade back to 11.0 (0.1.1 used this version) or even earlier. I'll report my findings here as well.

**Comment by TehNut** [comment]
Not our problem.

OR

Cauldron is not supported by TPPI, therefore this is not our problem.

We don't support people adding in mods and crashing the game due to it. Go bring it up with the Cauldron guys.

**Comment by Sayshal** [comment]
For more information check this issue on Mystcrafts' github: https://github.com/XCompWiz/Mystcraft-Issues/issues/66
