### ISSUE TITLE
Can't craft Sangumancy book in 0.1.4

### ISSUE THREAD

**Issue by Trostmm** [TPPIDev/TestPackPleaseIgnore2#300]
After updating to 0.1.4, Sanguimancy book no longer appears in NEI and doesn't appear to be craftable.
Tested in both single and multiplayer. Existing book seems to have disappeared from inventory as well.

**Comment by TehNut** [comment]
The book was changed. It's now called "Delving into Darkness" and *does* have a [recipe](https://github.com/Tombenpotter/Sanguimancy/blob/master/src/main/java/tombenpotter/sanguimancy/registry/SanguimancyGuide.java#L460.
