### ISSUE TITLE
Angel Wing wrong recipe?

### ISSUE THREAD

**Issue by shrimpsauce27** [TPPIDev/TestPackPleaseIgnore2#304]
Angel wing used to need bat wings to craft.
But since the 0.1.5 version of pack, it is 'impossible' to craft.
The new recipe need 2 'fire', which is impossible to obtain.(Uncrafting Table has been disabled)
Wish this would change back to normal recipe, or enable the uncrafting table...
Plz solve it =]

**Comment by TehNut** [comment]
0.1.5 is not stable. Downgrade if you don't want issues.
