### ISSUE TITLE
Texture/resource packs don't work

### ISSUE THREAD

**Issue by OCDSquirrel** [TPPIDev/TestPackPleaseIgnore2#306]
Tried to load a texture pack, but it didn't work.
I tried with 2.75 gigs, 3.5 gigs, and 4.5 gigs.
I have a nvidia 750ti graphics card (if that matters)
I installed optifine
Didn't disable fastcraft (Partly because I don't know how)
I've tried 128x, 64x, and 32x.
I **CAN** run 128x packs on Tekkit, so I'm fairly sure it's not my machine.

Log: http://pastebin.com/aJ1WbDfH

**Comment by TehNut** [comment]
Update your Fastcraft.
