### ISSUE TITLE
Modular Armour "Solar Helmet" upgrade costs power instead of providing it.

### ISSUE THREAD

**Issue by Doomgull** [TPPIDev/TestPackPleaseIgnore2#309]
When adding the "Solar Helmet" upgrade to the standard Modular Helmet, when outside with the sun excess power is lost and no power is gained. If indoors or at night, no power is lost.

Tested using no energy upgrade, Leadstone Energy upgrade, Reinforced Energy upgrade, and Hardened energy upgrades. Doesn't seem to matter if other power-using upgrades are installed at the same time.

Modular Armour v1.0.4-27

**Comment by TehNut** [comment]
TPPI version?

**Comment by Doomgull** [comment]
TPPI 0.1.5
