### ISSUE TITLE
Convert HEE Enderman Heads to Ender IO Enderman Heads

### ISSUE THREAD

**Issue by Slysam** [TPPIDev/TestPackPleaseIgnore2#312]
Currently when you kill an enderman(With an Ender, a Beheading Cleaver, or just normally), they can drop one of two heads. A HEE Enderman head, or an Ender IO enderman head. The HEE heads are just decoration. The Ender IO head is required for progression in the mod. Unfortunately there's no way to convert between the two, and no way to guarantee that you can get the Ender IO head(The actually useful one) when killing the mob.

With an already low drop rate on heads, even with looting/beheading, this seems unnecessarily punishing.

Is there a way a crafting recipe can be added to convert one to the other, or can they be oredicted so they can be run through the unifier or Mekanism's oredictionificator-thing?

**Comment by chylex** [comment]
The drop tables are separate, it doesn't mean "either HEE or Ender IO's head" so if there was a way to convert it, you would get pretty much double drops. Might be better to just disable the HEE ones, if there's a mod that can do that (HEE doesn't have that option).

**Comment by Slysam** [comment]
I've never seen the drop rate be high enough to get both at once, and you can get 7-8 creeper, 10+ zombie, and multiple skeleton heads by the time you see one enderman head(either HEE or EIO). I'm not convinced that double the drop rate would really be all that bad.

**Comment by tterrag1098** [comment]
Ender IO heads are meant to be quite rare. You can increase the drop rate
with a "The Ender" (empowerer) or a beheading tcon tool.

**Comment by shrimpsauce27** [comment]
once before a enderman drop me two heads, one enderio another hee one. This is quite strange , maybe disabling the hee enderman head from droping is better

**Comment by Slysam** [comment]
Yes I know you can increase the drop rates. I've been using an Ender with Looting III, and even tried a Cleaver with as much beheading as I could put on it.

I am aware that the drop rate is supposed to be low.

The problem is not that the drop rate is low, the problem is that there is another item that is clogging up the loot table for an -already low drop rate item-.

It's a simple solution, make HEE heads ordict to the Ender IO heads, or turn off the drop rate for the HEE heads.

**Comment by tterrag1098** [comment]
And you've been told that's not how it works. There are no loot tables for
entities. The two items do not affect each other.

**Comment by TehNut** [comment]
Non-issue
