### ISSUE TITLE
Soul fragment secondary recipe still taking 10% health

### ISSUE THREAD

**Issue by Grafic** [TPPIDev/TestPackPleaseIgnore2#317]
Crafting a soul fragment with the enhanced galgadorion block recipe still takes your health, but it shouldn't.

**Comment by UndeadZeratul** [comment]
Looks like they're aware, and that it can't be fixed? https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/217

**Comment by TehNut** [comment]
I'll probably replace this with a non-standard recipe to see if I can fix it.
