### ISSUE TITLE
Blood magic/Sanguimancy conflict, haste sigil in bound boots

### ISSUE THREAD

**Issue by LaycockBen** [TPPIDev/TestPackPleaseIgnore2#321]
There's a conflict between blood magic and Sanguimancy which causes the bound gear to kill you if you equip a sigil of haste.

Here's the report on Blood Magic: https://github.com/WayofTime/BloodMagic/issues/310
Here's the report on Sanguimancy: https://github.com/Tombenpotter/Sanguimancy/issues/33

The easiest way to fix it is to change the conflicting potionID in sanguimancy. (the conflicting ID being 101, the remove heart potion and it can be set in the sanguimancy config)

Thanks for all your hard work, guys!

**Comment by TehNut** [comment]
Fixed in dev long ago.
