### ISSUE TITLE
TPPI Tweaks doesn't tweak Mekanism v8 Recipies

### ISSUE THREAD

**Issue by Hastwell** [TPPIDev/TestPackPleaseIgnore2#324]
In a fresh install of TPPI2 v0.1.5 from the FTB Launcher, TPPI Tweaks fails to nerf Mekanism v8 recipes, in particular the Digital Miner, Atomic Alloy, and Atomic Disassembler. This seems to be caused by an exception raised during client/server start due to changed Mekanism code:

`Caused by: java.lang.NoSuchFieldError: AtomicDisassembler
    at tppitweaks.recipetweaks.modTweaks.MekanismTweaks.init(MekanismTweaks.java:29)`

The full stacktrace is available at http://pastebin.com/vH8SW5Df , and occurs during the loading of recipetweakingcore, which calls TPPI Tweaks.

**Comment by TehNut** [comment]
This has been known for... Months now. We've been preoccupied with real life.
