### ISSUE TITLE
CTD Caused by Mining Dense Ore

### ISSUE THREAD

**Issue by Marcellas** [TPPIDev/TestPackPleaseIgnore2#325]
When mining dense ores using a Fortune III, Auto-Smelt, Efficiency IV diamond pickaxe... I'm not sure if it is just that exact type or the combination of Fortune III and Auto-Smelt that causes the issue, but it happens regardless of the type of metal mined. It however does not effect coal or red stone dense ore that I have seen.

Here is the log: http://paste.ubuntu.com/12084524/

**Comment by TehNut** [comment]
This is a ttCore/EnderCore issue that is unfixable. @tterrag1098

**Comment by TehNut** [comment]
Oh, also a duplicate of #302

**Comment by Ianaver** [comment]
@Marcellas go to the EnderCore issue tracker and report it there, I suggest trying an updated version of enderio and endercore and testing that instead before reporting though (jenkins builds here http://ci.tterrag.com/job/EnderIO/ http://ci.tterrag.com/job/EnderCore/ ).

**Comment by TehNut** [comment]
No, do not go there. It is only fixable on DenseOre's side.

**Comment by Ianaver** [comment]
@TehNut it may be so but still maybe one of the authors know what caused it? I also need to test the new versions anyway since a lot has changed from when this issue was reported to now, ttcore is no more and is now endercore and autosmelt has received some improvements and bug fixes.

**Comment by Ianaver** [comment]
@Marcellas @TehNut Well I tested the newest version of endercore and dense ores and there are no more issues

**Comment by TehNut** [comment]
tterrag *is* the author.

**Comment by Ianaver** [comment]
@TehNut I said authors but I meant for both mods! XD either way its fixed now in newest version of endercore :P
