### ISSUE TITLE
Admin commands toolbox' pregen causes catastrophic performance loss

### ISSUE THREAD

**Issue by Baughn** [TPPIDev/TestPackPleaseIgnore2#328]
Probably.

See https://goo.gl/0GZpRw. I ran pregenspawn at Aug 26. 10:05, restarted the server immediately afterwards, and got alerted nine hours later due to low tick rates. Because of the lack of correlation, noisiness of that alert and extensive work at.. work, I didn't look at it at the time and didn't notice the enormous reduction.

Today I did. There are no other likely causes, so you folks may want to warn the other people playing TPPI2 before someone does the same.

Cross-posting to Mobius. I'll keep you posted, and see if I can verify.

Possible mitigations:
- Deleting any chunks which were generated at the time, by comparing incremental snapshots.

What could have gone better:
- Alerts which trigger too often are useless.

- There should be a TickRateWayTooLow alert.
- I'd previously noticed, during initial server launch, that pregenspawn causes some state corruption; that's why I restarted the server. However, no players were logged on back then, and I didn't log a bug at the time; there were no apparent lasting effects.

- And you folks probably ought to have a warning about this, as most folks don't have snapshots. ;-)

**Comment by TehNut** [comment]
I've always had issues with ACT, so I'm just going to drop it in `0.2.0` in favor of the one I use, [Chunkgen](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2223032-chunkgen-preload-chunks-on-demand).

**Comment by Baughn** [comment]
Fair enough, sounds like an idea.

For anyone else who runs across this: I confirmed the problem, via https://goo.gl/vJ34nW. What you should be looking at is the "ticks per second" graph; the moment I started generating (9:35 GMT) there's some jitter.

This manifests in the console as "Can't keep up! Did the system time change, or is the server overloaded? Running 2309ms behind, skipping 46 tick(s)", despite tick times showing the server as not-overloaded.

One mitigation is to use save-off, similarly to a... previous bug report I made... still about Mobius, but triggered by the nether...

Back in a sec.

**Comment by Baughn** [comment]
...fun. This turned out to be a three-way interaction between HQM, Servertools and Opis..

It can be fixed by removing every one simultaneously. Or, specifically, MobiusCore and HQM.

Other results were odd at best. I couldn't make it reproduce without having HQM installed during pregeneration, which means this is not a TPPI bug. I also can't make it reproduce without Opis. Differential symptoms, though: With MobiusCore installed, nothing shows up on Warmroast except a general increase in time used everywhere; without, HQM shows up heavily, both in updates and saves.

(Thus, presumably, the mitigation.)

I'll write a postmortem for the server this weekend. If you're interested in a copy, just ping me.
