### ISSUE TITLE
Memory Leak on Server

### ISSUE THREAD

**Issue by Marcellas** [TPPIDev/TestPackPleaseIgnore2#331]
I believe the culprit is BiomesO'Plenty... Didn't really see anything else that it point's to. It just tell player "timed out" when it disconnects/shuts down. 

Server Version TPPI2 0.2.1
Crash Log Paste: http://paste.ubuntu.com/12318307/

**Comment by TehNut** [comment]
What happens if you allocate 4Gb instead of 2Gb?

**Comment by TehNut** [comment]
Closing because this was probably caused by worldgen RAM usage on only 2Gb allocated.
