### ISSUE TITLE
Soujourner's Sash & 0.2.1

### ISSUE THREAD

**Issue by rherban** [TPPIDev/TestPackPleaseIgnore2#334]
After updating to 0.2.1, it appears that Soujourner's Sash (botania) no longer provides speed increase or ability to step up one block.  

Ring of Magnetization still works (haven't tested other botania things).

Tested in my saved world and a brand new world.

**Comment by tterrag1098** [comment]
The sash now requires mana to function. Have a mana tablet in your inventory and it will work.
