### ISSUE TITLE
Enderman Mining Assistant allows use of Last Millennium portal

### ISSUE THREAD

**Issue by TehNut** [TPPIDev/TestPackPleaseIgnore2#335]
Should only allow use of Deep Dark portal. Simply a case of not defining a specific meta value.

**Comment by Hazerdous** [comment]
Is the "Fixed in Next Version" tag referring to 0.2.4? 0.2.3 has these 2 recipes.
http://i.imgur.com/FkyG5UD.png
The top one accepts either Deep Dark or Last Millennium portal in both slots.

**Comment by TehNut** [comment]
Oh fuck me. I forgot we had multiple recipes registered...

https://github.com/TPPIDev/TPPI-Tweaks/blob/master/src/main/java/tppitweaks/tweak/recipe/TweakExtraUtilities.java#L80-L106
