### ISSUE TITLE
V0.2.2, Bug with Compressed Sawdust recipe

### ISSUE THREAD

**Issue by Hazerdous** [TPPIDev/TestPackPleaseIgnore2#336]
The normal recipe for Thermal Expansion's Compressed Sawdust (8 sawdust in a furnace/chest/donut/etc. shape), instead crafts 513 Pneumatic Servos.
From an ME Crafting Terminal, the servos cannot be pulled out of the crafting output, however in a vanilla crafting table (and probably other tables) they can.

Note: Compressed Sawdust uses the same ID as Pneumatic Servos (4875), the servo is MetaData 0, Compressed Sawdust is MetaData 513.

**Comment by TehNut** [comment]
[`new ItemStack(material, 513)`](https://github.com/TPPIDev/TPPI-Tweaks/blob/master/src/main/java/tppitweaks/tweak/recipe/TweakThermalExpansion.java#L111)

*sigh*

I missed a 1.
