### ISSUE TITLE
Enderium Flux Armor won't autocraft in AE2 

### ISSUE THREAD

**Issue by NetMasterFlex** [TPPIDev/TestPackPleaseIgnore2#346]
I successfully made all assembly patterns for the parts that are needed to craft the Ederium Flux Armor parts such as Helmet, Chestplate, Leggings, and boots.  For example the Endurium flux helmet is crafted using 4 Ederium Armor Plating and 1 Flux-Infused Helm.  These parts autocraft just fine, but when I created a pattern for the helm and requested one via the ME terminal, I get the qty screen, but clicking next doesn't do anything.  I'm currently running the the recommended version of TPPI2 both server and client.  I am able to craft the helmet in the crafting grid manually, just not in pattern autocrafting.

**Comment by TehNut** [comment]
It probably doesn't like the custom recipe type I use. Outsource it to a machine or don't autocracy it.
