### ISSUE TITLE
Stack of Thermal Expansion pneumatic servos craftable with sawdust

### ISSUE THREAD

**Issue by janeves** [TPPIDev/TestPackPleaseIgnore2#350]
in TPPI 0.2.2, Thermal Expansion pneumatic servos are craftable from sawdust.  NEI shows you would get 513 servos, but when crafted, it gives you 64.  The recipe does not work in AE crafting terminals, but does work in Vanilla and TiCon crafting stations.  We removed the recipe from our server with the following (disables it but still shows in NEI):

recipes.removeShaped(<ThermalExpansion:material:0>,[[<ThermalExpansion:material:512>, <ThermalExpansion:material:512>, <ThermalExpansion:material:512>], [<ThermalExpansion:material:512>, null, <ThermalExpansion:material:512>], [<ThermalExpansion:material:512>, <ThermalExpansion:material:512>, <ThermalExpansion:material:512>]]);

Not sure if 8 sawdust in a square is supposed to give something else.

**Comment by TehNut** [comment]
Update.

**Comment by TehNut** [comment]
Also, dupe of #336. Please search next time.
