### ISSUE TITLE
Night vision Goggle recipe no longer works

### ISSUE THREAD

**Issue by mpqholygrail** [TPPIDev/TestPackPleaseIgnore2#351]
![untitled](https://cloud.githubusercontent.com/assets/14862360/10124326/a527d9da-650f-11e5-9a44-67cb181f9f3e.png)

Tried to make nano suit helmet and goggle wont craft.

**Comment by mpqholygrail** [comment]
Version 0.2.3

**Comment by TehNut** [comment]
I fucking hate IC2. I'll fix it...

**Comment by TehNut** [comment]
In the future, default texture pack please. I couldn't tell what a few of those items were.

**Comment by mpqholygrail** [comment]
Ok sorry about that!  Default next time.
