### ISSUE TITLE
Latest version of TPPI2 (0.2.4) Forgemultipart Error

### ISSUE THREAD

**Issue by AuricPolaris** [TPPIDev/TestPackPleaseIgnore2#352]
Hi there Tehnut,

Latest version of TPPI2 (0.2.4) downloads an old version of Forgemultipart for the client (correct for the server). Image of the issue here: http://imgur.com/GoqYHfn. Basically it pulls .331 when it should be pulling .345 and FML dies inside.

**Comment by tterrag1098** [comment]
Isn't deploader the best? Everyone should use it. It never has any problems like this.

**Comment by TehNut** [comment]
Nah, this one isn't Deploader's fault. I have been shipping the `1.7.10` folder to *avoid* deploader. Not too sure why this is suddenly a problem, though. Nothing that depends on FMP was updated...

**Comment by tterrag1098** [comment]
Deploader updated it automatically on one side...I guess?

**Comment by TehNut** [comment]
Issue is that Assembler has a bug in it that requires some manual file manipulation inside the packaged zip. I forgot to do that manual work before shipping these zips.

**Comment by Marcellas** [comment]
Was there a workaround for this? I tried downloading the required forgemultipart but seem to only get CTD's.

**Comment by Baughn** [comment]
I got it to work by deleting the 1.7.10 directory entirely, and letting it download the version it wants.

Then deleting the older one, because for some reason it had grabbed two.

**Comment by Blackcatz1911** [comment]
I downloaded and replaced the ForgeMultipart with the version that is needed. (ForgeMultipart-1.7.10-1.2.0.336-universal.jar)

But it's not starting. Here is the crash report after startup: http://pastebin.com/EDEp0Qt4

**Comment by eiktyrner** [comment]
This is what I did, seems to work fine.

1. Delete folder: _TPPI2\minecraft\mods\1.7.10_
2. Start the game, it should download fresh copies of those files again.
3. Copy _ForgeMultipart-1.7.10-1.2.0.345-universal_ from _TPPI2\minecraft\common\1.7.10_ to _TPPI2\minecraft\mods\1.7.10_
4. Start the game
