### ISSUE TITLE
WAILA Config issue

### ISSUE THREAD

**Issue by KingDonFlon** [TPPIDev/TestPackPleaseIgnore2#353]
I tried rebinding the inventory to Tab and the playerlist to ^, but whenever I pressed Tab it would only hide the WAILA HUD. After deleting the WAILA configs, there was no more issue.

**Comment by TehNut** [comment]
Not really our issue.

**Comment by KingDonFlon** [comment]
As the provided configs seem to be messing the hotkeys, it kinda is.
