### ISSUE TITLE
0.2.4 crash when placing mekanism induction casing in crafting grid

### ISSUE THREAD

**Issue by dieselfuelonly** [TPPIDev/TestPackPleaseIgnore2#354]
Client crashes when placing the mekanism induction casing into a crafting grid - includes AE2 pattern terminal, AE2 crafting terminal, and a vanilla crafting table

http://pastebin.com/WtUEj0bD

**Comment by TehNut** [comment]
I swear I fixed that... Maybe I didn't drop in the new Mek build then? #348
