### ISSUE TITLE
Blizz shooting blizz powder and dropping snowballs

### ISSUE THREAD

**Issue by mpqholygrail** [TPPIDev/TestPackPleaseIgnore2#359]
TPPI2 version 0.2.5  The blizz spawning will drop only snowballs and are shooting blizz powder.

**Comment by TehNut** [comment]
Explain..?

**Comment by mpqholygrail** [comment]
Sorry i was updating comment as you responded

**Comment by mpqholygrail** [comment]
![2015-10-25_17 13 18_2](https://cloud.githubusercontent.com/assets/14862360/10718568/e5a96126-7b3b-11e5-859d-a1f83bd29896.png)
![2015-10-25_17 13 33](https://cloud.githubusercontent.com/assets/14862360/10718572/f74e87ee-7b3b-11e5-826f-120ca0dbd78f.png)

**Comment by mpqholygrail** [comment]
Hope this helps

**Comment by TehNut** [comment]
I'm still not sure what the issue is...

**Comment by mpqholygrail** [comment]
Ah never mind, looks like they are dropping the bliz rods.
