### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bsasealteam6** [TPPIDev/TestPackPleaseIgnore2#381]
Everytime I accidentally try to use NEI to warp something into my inventory when my inventory if full, it crashes the game back to the FTB launcher.  I have set the game to have access to 15GB of RAM.

**Comment by KingofGamesYami** [comment]
You have no proof that your game crashed.

**Comment by bookerthegeek** [comment]
Also, this is a known issue in NEI and will happen with only that mod installed so not a pack issue.
