### ISSUE TITLE
Biomes o Plenty requires Forge 1566 on Server?

### ISSUE THREAD

**Issue by MrDanCorbs** [TPPIDev/TestPackPleaseIgnore2#383]
Updated my server today...

Getting an error causing the server to crash that reads BoP requires Forge...1566. This then causes the server to stop. I have tried manually installing 1566 alongside the latest 1614 but to no avail. No issue yesterday, but I have a feeling Forge was past 1566 when the pack was last updated anyway.

Any ideas as to how to fix?

**Comment by XxXYaJrAbXxX** [comment]
It will require the same version of forge as the client is running. Please post the error to a website and link so the community can assist further: www.pastebin.com

**Comment by MrDanCorbs** [comment]
The relevant excerpt from the crash report is as follows:

Time: 03/11/16 16:14
Description: Exception in server tick loop

Missing Mods:
	Forge : [10.13.4.1566,)

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:260)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

However in the server log, it reads that it is crashing because BoP is calling on it.

**Comment by XxXYaJrAbXxX** [comment]
What is your server running?

**Comment by XxXYaJrAbXxX** [comment]
Bukkit, Forge, Spigot, KCauldron, Thermos etc?

**Comment by MrDanCorbs** [comment]
Forge. The pack is downloaded from the FTB Launcher.

**Comment by XxXYaJrAbXxX** [comment]
You should only be running Forge version 1558 for TPPI2 not 1614

**Comment by MrDanCorbs** [comment]
I've tried that, and as I say, BoP is calling on 1566 which is causing the server to crash.

**Comment by MrDanCorbs** [comment]
I've found a temporary fix - starting the server from the Forge 1566 Java file (as opposed to minecraft-server.jar) causes everything to load as it should.

**Comment by XxXYaJrAbXxX** [comment]
That would explain a lot, the MinecraftServer.jar should be used as a reference for Forge, you will always need to run the Forge.jar file instead.

**Comment by MrDanCorbs** [comment]
Never had any issues running it off that until this update.

But for now, at least, the issue is resolved.

**Comment by TehNut** [comment]
Wrong repo. Read the update thread.
