### ISSUE TITLE
Carpenter's Block Issues.

### ISSUE THREAD

**Issue by Wervern** [TPPIDev/TestPackPleaseIgnore2#39]
Carpenter's blocks can't be placed when holding shift.

When broken, Carpenter's doors and beds (possibly others) are apparently picked up as the top or bottom half of the two block object. The other half is not picked up. They appear as blank icons in the inventory and can be placed, but they show up as only half the object and are destroyed if broken again.

**Comment by TehNut** [comment]
Doesn't happen anymore.
