### ISSUE TITLE
Fake Players can perform Blood Magic

### ISSUE THREAD

**Issue by FakoTheGreat** [TPPIDev/TestPackPleaseIgnore2#45]
Fake players such as the Autonomous Activator from Thermal Expansion are capable of activating Blood Magic blocks and items, allowing a player to fill their soul network and utilize expensive options from Blood Magic without worry of dying.

Tested with the following:
Apprentice Blood Orb bound to player - The Autonomous Activator used repeatedly, filling player's blood pool to maximum.
Unbound Bound Sword - Sword was bound to CoFH, meaning it can be left as "active" permanently, only becoming a hazard to the player using if they didn't give an orb to an AA.
Imperfect Ritual Stone - AA can right click the stone without fear of death, activating rituals continuously. Couple with a dagger of sacrifice in a Dynamism Tablet (AA lost ability to use) and you can easily automate filling an altar without having to touch rituals.

**Comment by esKaayY** [comment]
Still an issue in the latest version apparently :/

**Comment by WayofTime** [comment]
Not to be an ass, but you are going to need to give the actual situations in which my checks fail to verify the player.

**Comment by esKaayY** [comment]
No worries. Retrieving now

**Comment by TehNut** [comment]
Hilburn has a mini-mod that apparently fixes this. Seeing if I can get my hands on it.

**Comment by TehNut** [comment]
Hilburn has now PR'ed a fix to BloodMagic. https://github.com/WayofTime/BloodMagic/pull/237

**Comment by TehNut** [comment]
Fixed as of https://github.com/WayofTime/BloodMagic/commit/e47e41fda980cb956f3abbda43717fa6d0629171
