### ISSUE TITLE
Emerald NEI crash

### ISSUE THREAD

**Issue by HikariLagann** [TPPIDev/TestPackPleaseIgnore2#65]
I'm not sure how easily this can be fixed, but I will post it. When you check the recipe uses for an emerald in NEI, it shows 1/44 possible uses. You can check 1 through 12 just fine and 15-44 just fine, but once you hit the next arrow for 13/44, or if you the back arrow for 14/44, it crashes you to the desktop. Have repeated this a few times to see if the crash was just random or not. Thus it seems recipe pages 13/44 and 14/44, using emeralds, crash the client.

page 13/44 crash: http://paste.ubuntu.com/9351020/
page 14/44 crash: http://paste.ubuntu.com/9351030/

**Comment by TehNut** [comment]
Fixed in newer binnie versions
