### ISSUE TITLE
Ztones Recipes

### ISSUE THREAD

**Issue by esKaayY** [TPPIDev/TestPackPleaseIgnore2#73]
Very expensive for purely decorative blocks. Will have to adjust

**Comment by TehNut** [comment]
Idea: See if we can implement the Ztone Tile into the chisel. So we remove all recipes except the tile. Then tile in chisel gives all the different options for the Ztones Blocks with a meta of 0.

**Comment by TehNut** [comment]
Done when [ChiselTones](http://minecraft.curseforge.com/mc-mods/228004-chiseltones) was added.
