### ISSUE TITLE
Infernal Mind Spiders

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#76]
If you're going to keep them infernal for the love of god make them not be able to be destructive. Having them disarm/blind you/etc is fine. The amount of times I have had to run away from the explosion causing, lightning striking, piles of shit so they don't destroy my base and machines is getting annoying. 

We are already punished enough from getting tons of warp with the damn normal negative effects.

I know you are evil esKaayY but this is seriously too evil.

**Comment by esKaayY** [comment]
Closed here: https://github.com/TPPIDev/TestPackPleaseIgnore2/commit/1a30b346eaadd9fbbd23f1c1b33a1651e2287379
