### ISSUE TITLE
Cardboard Box blacklist is empty

### ISSUE THREAD

**Issue by tterrag1098** [TPPIDev/TestPackPleaseIgnore2#77]
Things that need to be blacklisted:

- [ ] Nodes
- [ ] Black Holes
- [ ] Refinery+
- [ ] ???

**Comment by ryanayoung** [comment]
should probably add factorization barrels.  They never really worked before, but now it will box it up, but when placed creates a "missing entity" in the block, and the barrel/contents of the barrel are deleted.
