### ISSUE TITLE
Extra Utils. Generators don't power adjacent machines

### ISSUE THREAD

**Issue by jamesblack** [TPPIDev/TestPackPleaseIgnore2#78]
I dunno if you guys want issues that i found, while just playing after assembling the modlist by hand. Extra Utilities Generators don't power adjacent machines currently...

This is the same issue as described below:

http://forum.feed-the-beast.com/threads/1-0-3-extra-utilities-generators-dont-output-power-to-nearby-machines.58496/

**Comment by esKaayY** [comment]
This is because ExU isn't updated to the latest RF API in COFH. Noted.

**Comment by tterrag1098** [comment]
Actually it is. He just didn't *implement* the new API classes into his checks.

**Comment by Donmyster** [comment]
It seems to be fixed with the new update.

**Comment by TehNut** [comment]
Checked, still an issue

**Comment by Donmyster** [comment]
There must be another variable to this then because I've been powering a metallurgic infuser with two survival generators since the restart.

**Comment by tterrag1098** [comment]
Metallurgic infusers are not affected by the bug.

**Comment by tterrag1098** [comment]
None of mekanism is.
