### ISSUE TITLE
Ores from Custom Things not localized

### ISSUE THREAD

**Issue by Sovereignty89** [TPPIDev/TestPackPleaseIgnore2#80]
As the title says. The ores added by Custom Things are not localized. They show up as "tile.customthings.ore.orename.name".

Also they can be mined in one hit, even with wood tools.
Mining bauxite with stone pickaxe! Because my wooden one broke.

**Comment by tterrag1098** [comment]
@TehNut didn't set the hardness values, not my fault.

On the localization thing, still looking into that.

**Comment by esKaayY** [comment]
Fixed with latest update.
