### ISSUE TITLE
Finding Ztones tools in dungeon chests.

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#84]
I thought Nut disabled this.

Not sure though.

http://puu.sh/dYHuD/11d664f29f.jpg

**Comment by esKaayY** [comment]
I think I can change it with toomuchloot. I'll look into it.

**Comment by TehNut** [comment]
Yeah, I disabled it. We added it for the blocks, not the items. Apparently ZTones config isn't on the Github, so it generated a fresh one. Will fix.

**Comment by TehNut** [comment]
Fixed in d749f6ca5b76145d6b99d5d7e4e92ad324a7c405

**Comment by tterrag1098** [comment]
Mini charcoal is kinda useful :L
