### ISSUE TITLE
Aluminum dust (gregtech) does not work in TiCon smeltery

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#88]
Nor does the ingots you get when you smelt the dust.

**Comment by esKaayY** [comment]
This is a known issue and nothing can be done about it due to the incompatibilities between gt and tic

**Comment by Yulife** [comment]
Just curious, not even Modtweaker?

**Comment by TehNut** [comment]
We don't provide modtweaker or minetweaker scripts to the clients. It's not how we do things.
