### ISSUE TITLE
Bronze Crafting Recipe Balance

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#97]
Crafting 1 tin ingot and 3 copper ingots together gives one bronze ingot, a la Gregtech. In previous iterations of the pack, it would yield either 4 bronze, or as 1.6 had it 3. I don't see getting 4 as much of a balance issue, considering the abundance of copper and tin in addition to the ease at which you can smelt the stuff together to get 4 ingots.

**Comment by Sovereignty89** [comment]
This isn't something Gregtech does. Gregtech does not allow you to craft bronze like that. You get bronze by adding the dust together, 3 copper and 1 tin and you get 3 bronze dust(lose 25%), you get the dust by using the ingot together with the mortar. This recipe must be added by something else.
http://ftb.gamepedia.com/Bronze

**Comment by HaroldDaFrog** [comment]
could it be perhaps gregtech modifying the forestry recipe?

**Comment by TehNut** [comment]
Until GT was added, it produced 4. The 1 produced is new. However, it should probably be disabled all together.

**Comment by esKaayY** [comment]
Can't be done via configs. If you wish to change it, it'll have to be done through tppitweaks. Personally, I don't see a problem with losing efficiency when crafting dusts by hand compared to machines, but that's just me.
